version: '3.7'
services:
  db:
    container_name: practice_pg
    image: postgres:14.1
    restart: always
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql@14.1/data
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgresql@14.1/data
volumes:
  db: